version: "3.9.16"

services:
  vpm:
    image: vagas-pra-mim
    container_name: vagas-pra-mim
    volumes:
      - /dev/shm:/dev/shm
      - ./src:/webapp/src
      - ./static:/webapp/static
      - ./language:/webapp/language
      - ./logs:/webapp/logs
      - ./templates:/webapp/templates
      - type: bind
        source: ./app.py
        target: /webapp/app.py
    ports:
      - 5001:5001
    working_dir: /webapp
    environment:
      DATABASE_STRING: sqlite+pysqlite:///vpm.sqlite

volumes:
  vpm-data:
