# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


driver = webdriver.Chrome()
vars = {}


driver.get("https://recruitingbypaycor.com/career/JobIntroduction.action?clientId=8a7882525b41aa84015b59059b235352&id=8a7885a8766d9a3c0176f868c234296d&source=&lang=en")
iframe = driver.find_element(By.CSS_SELECTOR, 'iframe#gnewtonIframe')
driver.switch_to.frame(iframe)
els = driver.find_elements(By.XPATH, "//body/*")
txt = ""
for el in els:
   txt += el.text
print(txt)
driver.switch_to_default_content()
driver.quit()
  