[tox]
envlist = py{37}

[testenv]
description = run unit tests
deps =
    -r requirements.txt
    -r test-requirements.txt
commands =
    export PYTHONPATH=$(pwd)
    python ./utils/add_fake_data_to_databse.py
    python -m pytest

[flake8]
# https://black.readthedocs.io/en/stable/guides/using_black_with_other_tools.html#minimal-configuration
max-line-length = 100
extend-ignore = E203,E701
per-file-ignores =
    # 'from module import *' used; unable to detect undefined names
    # Name may be undefined, or defined from star imports: module
    __init__.py:F403,F405

[testenv:linting]
commands =
    flake8 --exclude=venv --max-line-length=100