name: Heart beating

on:
  schedule:
    - cron: "*/1 * * * *"

permissions:
  contents: read

jobs:
  heart-beating:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4
      - name: heart beating
        run: |
          wget https://vagaspramim.onrender.com/ads.txt
